"""Utilities package."""

from src.utilities.dataframe_utils import (
    add_bronze_metadata,
    broadcast_join,
    cache_df,
    cast_columns,
    dedupe_keep_latest,
    drop_exact_duplicates,
    generate_load_id,
    generate_run_id,
    null_safe_fill,
    sha256_expr,
    standardize_email,
    standardize_phone,
    standardize_string_columns,
    write_to_dlq,
)
from src.utilities.delta_helpers import (
    enable_liquid_clustering,
    history,
    maintain_entity,
    merge_delta,
    optimize_table,
    table_exists,
    time_travel,
    vacuum_table,
    write_delta,
)
from src.utilities.exceptions import (
    DataQualityError,
    DeadLetterError,
    HealthcareLakehouseError,
    IngestionError,
    MergeConflictError,
    SchemaEvolutionError,
    TransformationError,
    with_retry,
)
from src.utilities.spark_session import get_spark, stop_spark
from src.utilities.databricks_runtime import (
    configure_writable_volume,
    patch_input_file_name,
    prepare_databricks_runtime,
    resolve_notebook_spark,
)

__all__ = [
    "add_bronze_metadata",
    "broadcast_join",
    "cache_df",
    "cast_columns",
    "dedupe_keep_latest",
    "drop_exact_duplicates",
    "generate_load_id",
    "generate_run_id",
    "null_safe_fill",
    "sha256_expr",
    "standardize_email",
    "standardize_phone",
    "standardize_string_columns",
    "write_to_dlq",
    "enable_liquid_clustering",
    "history",
    "maintain_entity",
    "merge_delta",
    "optimize_table",
    "table_exists",
    "time_travel",
    "vacuum_table",
    "write_delta",
    "DataQualityError",
    "DeadLetterError",
    "HealthcareLakehouseError",
    "IngestionError",
    "MergeConflictError",
    "SchemaEvolutionError",
    "TransformationError",
    "with_retry",
    "get_spark",
    "stop_spark",
    "configure_writable_volume",
    "patch_input_file_name",
    "prepare_databricks_runtime",
    "resolve_notebook_spark",
]
